name: Artifacts (Package)

on:
  push:
    branches: [ bottlesbuild ]
  workflow_dispatch:

jobs:
  build-artifacts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Prepare environment (none-tag)
      if: github.ref_type != 'tag'
      run: |
        export ARTIFACT="build/nvcuda"
        echo "ARTIFACT=${ARTIFACT}" >> $GITHUB_ENV

    - name: Setup problem matcher
      uses: Joshua-Ashton/gcc-problem-matcher@v3

    - name: Build
      uses: Joshua-Ashton/arch-mingw-github-action@9cdb815264bce7a6346927521b176f578982679d
      with:
        command: |
          ./package-release.sh "${{ env.ARTIFACT }}"

    - name: Create tarball
      run: tar cvfJ "nvcuda.tar.xz" -C "./${{ env.ARTIFACT }}" .

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nvcuda
        path: "nvcuda.tar.xz"
        if-no-files-found: error
